#!/bin/sh

AWS=${AWS:-/etc/letsencrypt/aws}
DIR=${DIR:-/a/letsencrypt}
DOCKER=${DOCKER:-docker}
IMG=${IMG:-certbot/dns-route53}
NGINX=${NGINX:-nginx}
NGINX_CONF=${NGINX_CONF:-/config/nginx/nginx.conf}

err() {
  [ $? -ne 0 ] && [ -n "$HEALTHCHECK" ] && curl -s -m 10 --retry 5 -o /dev/null "$HEALTHCHECK/fail"
}
trap err EXIT

set -e

[ -n "$HEALTHCHECK" ] && curl -s -m 10 --retry 5 -o /dev/null "$HEALTHCHECK/start"

$DOCKER run --rm -e "AWS_CONFIG_FILE=$AWS" -v "$DIR:/etc/letsencrypt" $IMG renew -nq
$DOCKER exec "$NGINX" nginx -c $NGINX_CONF -s reload

[ -n "$HEALTHCHECK" ] && curl -s -m 10 --retry 5 -o /dev/null "$HEALTHCHECK"

exit 0